#+STARTUP: showall



* OSM maps in Emacs and Org mode

  =osm-maps.el= provides functions to produce SVG images for tracks.  Tracks are
  made of pairs of coordinates.

  Currently, two basic uses are possible:

  1. Create an SVG image, that uses the tiles online on the openstreetmap.org
     servers.
  2. Download the tiles to a local directory and produce SVG images, that use
     those local image tiles as background (caching).


* Setup

  Just make sure =osm-maps.el= and =org-osm-link.el= are in your load-path, and add
  this line to your setup (=.emacs= probably):

  : (require 'org-osm-link)

  After restarting Emacs (or evalutating the code above) you may customize the
  new OSM features:

  : M-x customize-group RET osm-maps RET

  The most important feature is to adjust ist the caching behaviour.  This is
  currently controlled by the variable =osm-do-cache=.  If this variable is
  non-nil, the background tiles are downloaded and stored to disc for local
  (fast) use.

  Be careful!  Caching can take hours on slow connections for bigger areas.  But
  only once per zoom level though.  The area I use for my training diary uses
  316 MB disc space currently (I just use three zoom levels).

  Producing the images without caching is just as fast, but you will need to be
  online when browsing the results.  In the future I hope to restrict the
  caching to certain customizable areas.


* What do the links look like?

  A link to a track looks like this:

  : [[track:((9.707032442092896 52.37033874553582)(9.711474180221558 52.375238282987))FILENAME.svg][DESCRIPTION]]
  :                ^^^               ^^^
  :             longitude          latitude

  Negative latitudes are on the southern hemisphere.

  Once you click the link the image is created for you and shown in a new
  buffer.  Existing tracks are re-used.  You may provide a custom funciton to
  show the images.  See the docs for the custom variable
  =`osm-org-image-viewer-function=' in =org-osm-link.el=.


* How to publish the maps with HTML?

  See the docs for osm-publish-map-for-html.


* Implemented features

  - Download and caching of background tiles.
  - Optionally use online resources as background tiles.
  - Working Org links.  Click a =track:= link pops up a map of the track.  The map
    is created if it does not exist yet (SVG files).
  - HTML publishing of links and maps.
  - Interactive creation of Org =track:= links.


* Aims and ideas

  - *Better documentation*.
  - Configure zoom levels and areas to cache the images for.  Produce SVGs with
    online tiles for tracks outside of those areas, use the cached tile for
    tracks in those areas.
  - Produce a draggable JavaScript map on HTML export.
  - Reuse the draggable JavaScript map to draw new tracks.
  - Allow for POIs.
  - Draw kilometer or mile markers.
  - Configure start and destination icons.
  - Allow for multiple tracks on one map.
  - Draw a legend.
  - Restrict images to a certain size and adjust the zoom level accordingly.
  - HTML export: Produce thumbnails and link to bigger images.



# Local Variables:
# mode: Org
# mode: iimage
# End:
